name: "Test Backend"
description: "Installation Java et exécution des tests Spring Boot (Unitaires et Intégration)"

runs:
  using: "composite"
  steps:
    - name: Configuration de Java (Temurin JDK 21)
      uses: actions/setup-java@v5
      with:
        java-version: "21"
        distribution: "temurin"
        cache: "maven"

    - name: Exécution des tests Spring Boot
      shell: bash
      working-directory: Backend/developpement
      run: mvn test