spring.application.name=battlecreator

# Port d'écoute
server.port=8080

# Connexion à la base (postgres est le nom du service Docker)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Pilote PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA / Hibernate (crée/met à jour les tables automatiquement)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port dynamique (Alwaysdata injecte $PORT, par défaut 8080 en local)
server.port=${PORT:8080}

# JWT
security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY}
security.jwt.expiration-time=${SECURITY_JWT_EXPIRATION_TIME}
