spring.application.name=battlecreator

# Port d'écoute
server.port=8080

# Connexion à la base (postgres est le nom du service Docker)
spring.datasource.url=jdbc:postgresql://postgres:5432/db_battle_creator
spring.datasource.username=app
spring.datasource.password=app_secret
spring.datasource.driver-class-name=org.postgresql.Driver 

# Hibernate ne fait aucune opération DDL sur le schéma, donc ni validation, ni création, ni modification de tables
# spring.jpa.hibernate.ddl-auto=none
# Hibernate fait une mise à jour entres entités/objets java et tables BDD PostgreSQL
spring.jpa.hibernate.ddl-auto=update
# ou
# Hibernate: aucune création automatique, aucune modification, seulement contrôle de cohérence
# spring.jpa.hibernate.ddl-auto=validate
# ou 
# # Hibernate : création automatique des tables au démarrage + suppression des tables à l'arrêt (util pour passer les tests lors du build : mvn clean package)
# spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
# Logs Hibernate (optionnel, à désactiver en prod)
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false
# # CONFIG V1 # #
# spring.application.name=battlecreator

# # Port d'écoute (8080 par défaut)
# # server.port=8081

# # Connexion à la base (Note : on utilise "postgres" car c'est le nom du service Docker)
# spring.datasource.url=jdbc:postgresql://postgres:5432/db_battle_creator
# spring.datasource.username=app
# spring.datasource.password=app_secret
# spring.datasource.driver-class-name=org.postgresql.Driver

# # Hibernate: aucune création automatique, aucune modification, seulement contrôle de cohérence
# spring.jpa.hibernate.ddl-auto=validate
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# # # Hibernate : Création automatique des tables à partir de tes objets Java si elle n'existe pas, ou mise à jour si besoin
# # spring.jpa.hibernate.ddl-auto=update
# # spring.jpa.show-sql=true
# # spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# JWT

security.jwt.secret-key=9c14cadd104b002192aedcd27ecbfd23a80ff96095c3eb6403b9b18261d1b264
# en millisecondes
security.jwt.expiration-time=900000