spring.application.name=battlecreator

# Port d'écoute
server.port=${PORT:8080}

# Connexion à la base (valeurs par défaut pour l'environnement Docker Compose)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/db_battle_creator}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:app}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:app_secret}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY:9c14cadd104b002192aedcd27ecbfd23a80ff96095c3eb6403b9b18261d1b264}
security.jwt.expiration-time=${SECURITY_JWT_EXPIRATION_TIME:86400000}