services:
  # L'application Java
  app:
    build: .
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Indiquer seulement le nom sans valeur permet à Docker d'hériter 
      # de la variable d'environnement transmise par GitHub Actions / l'OS
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      # Ajoute ces lignes :
      - SECURITY_JWT_SECRET_KEY=${SECURITY_JWT_SECRET_KEY}
      - SECURITY_JWT_EXPIRATION_TIME=${SECURITY_JWT_EXPIRATION_TIME}

  # La base de données
  postgres:
    image: postgres:16-alpine
    container_name: db_postgresql_battle_creator
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_secret
      POSTGRES_DB: db_battle_creator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d db_battle_creator"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

# # CONFIG V1 # #
# services:
#   # L'application Java
#   app:
#     image: maven:3.9-eclipse-temurin-21
#     working_dir: /app
#     volumes:
#       - .:/app                  # On monte ton code source dans le conteneur
#       - maven-cache:/root/.m2   # Cache pour ne pas retélécharger les libs Java
#     ports:
#       - "8080:8080"
#     depends_on:
#       postgres:
#         condition: service_healthy # Attend que la BDD soit vraiment prête
#     command: ./mvnw spring-boot:run

#   # La base de données
#   postgres:
#     image: postgres:16-alpine
#     container_name: db_postgresql_battle_creator
#     environment:
#       POSTGRES_USER: app
#       POSTGRES_PASSWORD: app_secret
#       POSTGRES_DB: db_battle_creator
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     healthcheck: # Teste si Postgres accepte les connexions
#       test: ["CMD-SHELL", "pg_isready -U app -d db_battle_creator"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

# volumes:
#   postgres_data:
#   maven-cache: